### ISSUE TITLE
FR: strict deps for bzl_library

### ISSUE THREAD

**Issue by Capstan** [bazelbuild/bazel-skylib#16] opened 2018-01-19 13:47 UTC
Suggest a model where `srcs` are parsed just enough to evaluate [`load()` statements](https://docs.bazel.build/versions/master/be/functions.html#load) to ensure the `label`'s `.bzl` file is a member of one of `deps`'s `SkylarkLibraryInfo`'s `srcs`, i.e., a direct dependency rather than a  transitive dependency.

**Comment by tetromino** [comment] 2021-04-17 16:08
Currently, `bzl_library` does not do any loading/parsing/processing of Starlark files at all: it only operates on file names, and is happy as long as they end in `\.bzl`.

Adding a strict dep check would require interpreter support and some careful thought.

**Comment by tetromino** [comment] 2021-04-17 16:34
Duplicate of #50 (keeping that as primary because it has more discussion).

**Closed by tetromino** 2021-04-17 16:34 UTC
Labels: P4, enhancement
